### ISSUE TITLE
希望添加arm架构的linux包

### ISSUE THREAD

**Issue by catcherxuefeng** [cuiocean/ZY-Player#617]
可以为arm架构打包AppImage吗？

**Comment by YangtseSu** [comment]
$ git clone https://github.com/Hunlongyu/ZY-Player
$ cd ZY-Player
$ yarn electron:build

**Comment by buvta** [comment]
如果yarn electron:build不能运行，请先执行下npm install或yarn install

**Comment by yaoyuanzy** [comment]
apt install -y  npm
下载解压源码 npm install 

> zy@2.8.8 postinstall
> electron-builder install-app-deps

  • electron-builder  version=22.7.0

added 1697 packages in 21m

100 packages are looking for funding
  run `npm fund` for details
这里的依赖 build 出现异常
root@phicomm-t1:~/ZY-Player-2.8.8# yarn electron:build
yarn run v1.23.0-20220130.1630
$ vue-cli-service electron:build
 ERROR  Error: Cannot find module './addons/build'
Require stack:
- /root/ZY-Player-2.8.8/node_modules/xregexp/lib/index.js
- /root/ZY-Player-2.8.8/node_modules/yargs/node_modules/decamelize/index.js
- /root/ZY-Player-2.8.8/node_modules/yargs/build/lib/usage.js
- /root/ZY-Player-2.8.8/node_modules/yargs/build/lib/yargs.js
- /root/ZY-Player-2.8.8/node_modules/yargs/yargs.js
- /root/ZY-Player-2.8.8/node_modules/yargs/index.js
- /root/ZY-Player-2.8.8/node_modules/vue-cli-plugin-electron-builder/index.js
- /root/ZY-Player-2.8.8/node_modules/@vue/cli-service/lib/Service.js
- /root/ZY-Player-2.8.8/node_modules/@vue/cli-service/bin/vue-cli-service.js



root@phicomm-t1:~/ZY-Player-2.8.8# curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --nightly
root@phicomm-t1:~/ZY-Player-2.8.8# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
root@phicomm-t1:~/ZY-Player-2.8.8# yarn --version
1.23.0-20220130.1630
root@phicomm-t1:~/ZY-Player-2.8.8# yarn install  
yarn install v1.23.0-20220130.1630
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning @vue/cli-plugin-babel > webpack > watchpack > chokidar > fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
warning @vue/cli-plugin-babel > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
[2/4] Fetching packages...
[####################------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------[###################--info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "bootstrap-vue > bootstrap@4.6.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > sass-loader@10.1.1" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.7.0
Done in 330.55s.

root@phicomm-t1:~/ZY-Player-2.8.8# yarn electron:build
 INFO  Building app with electron-builder:
  • electron-builder  version=22.7.0 os=5.15.58-arm-64
  • description is missed in the package.json  appPackageFile=/root/ZY-Player-2.8.8/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/root/ZY-Player-2.8.8/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • packaging       platform=linux arch=arm64 electron=13.6.9 appOutDir=dist_electron/linux-arm64-unpacked
  • building        target=snap arch=arm64 file=dist_electron/zy_2.8.8_arm64.snap
  • building        target=AppImage arch=arm64 file=dist_electron/ZY Player-2.8.8-arm64.AppImage
2022/08/03 13:11:56.607931 cmd_run.go:1044: WARNING: cannot create user data directory: failed to verify SELinux context of /root/snap: exec: "matchpathcon": executable file not found in $PATH
Ignoring '--target-arch' flag.  This flag requires --destructive-mode and is unsupported with Multipass and LXD build providers.
Issues while validating snapcraft.yaml: The 'description' property does not match the required schema: '' is not a valid description string.
  ⨯ exit status 2

这里的报错不用 care 

root@phicomm-t1:~/ZY-Player-2.8.8/dist_electron/linux-arm64-unpacked# ll
total 178676
-rw-r--r-- 2 root root      1096 Aug  3 13:11 LICENSE.electron.txt
-rw-r--r-- 2 root root   5286034 Aug  3 13:11 LICENSES.chromium.html
-rwxr-xr-x 2 root root     52768 Aug  3 13:11 chrome-sandbox
-rw-r--r-- 2 root root    141930 Aug  3 13:11 chrome_100_percent.pak
-rw-r--r-- 2 root root    208519 Aug  3 13:11 chrome_200_percent.pak
-rw-r--r-- 2 root root  10413488 Aug  3 13:11 icudtl.dat
-rwxr-xr-x 2 root root    224704 Aug  3 13:11 libEGL.so
-rwxr-xr-x 2 root root   6919608 Aug  3 13:11 libGLESv2.so
-rwxr-xr-x 2 root root   2473040 Aug  3 13:11 libffmpeg.so
-rwxr-xr-x 2 root root  16944000 Aug  3 13:11 libvk_swiftshader.so
-rwxr-xr-x 2 root root   4442584 Aug  3 13:11 libvulkan.so.1
drwxr-xr-x 2 root root      4096 Aug  3 13:11 locales
drwxr-xr-x 2 root root      4096 Aug  3 13:11 resources
-rw-r--r-- 2 root root   5093175 Aug  3 13:11 resources.pak
-rw-r--r-- 2 root root     48329 Aug  3 13:11 snapshot_blob.bin
drwxr-xr-x 2 root root      4096 Aug  3 13:11 swiftshader
-rw-r--r-- 2 root root    165528 Aug  3 13:11 v8_context_snapshot.bin
-rw-r--r-- 2 root root       107 Aug  3 13:11 vk_swiftshader_icd.json
-rwxr-xr-x 2 root root 130507120 Aug  3 13:11 zy
但这里还是不能运行，浪费时间了

**Comment by YangtseSu** [comment]
给你个现成饭吧。
zy player 2.8.8 arm64 appimage 和deb

链接: https://pan.baidu.com/s/19SlucTNtsH10o9h7c5Qzfw 提取码: 7hfd 复制这段内容后打开百度网盘手机App，操作更方便哦 
--来自百度网盘超级会员v5的分享

**Comment by yaoyuanzy** [comment]
> 给你个现成饭吧。 zy player 2.8.8 arm64 appimage 和deb
> 
> 链接: https://pan.baidu.com/s/19SlucTNtsH10o9h7c5Qzfw 提取码: 7hfd 复制这段内容后打开百度网盘手机App，操作更方便哦 --来自百度网盘超级会员v5的分享

感谢感谢，老哥 V5
